# Generated by Django 5.0.2 on 2024-03-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='Test', max_length=50),
        ),
    ]
